import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case simplifiedChinese = "zh-Hans"
    case english = "en"

    static let preferenceKey = "interfaceLanguageV1"
    var id: String { rawValue }
    var nativeName: String { self == .english ? "English" : "简体中文" }
    var appName: String { self == .english ? "Right-Click Assistant" : "右键助手" }

    static var current: AppLanguage {
        if let raw = SharedPreferences.defaults.string(forKey: preferenceKey), let language = AppLanguage(rawValue: raw) {
            return language
        }
        return Locale.preferredLanguages.first?.hasPrefix("zh") == true ? .simplifiedChinese : .english
    }
}

enum L10n {
    static func tr(_ key: String, _ arguments: String...) -> String {
        text(key, arguments: arguments, language: .current)
    }

    static func text(_ key: String, arguments: [String] = [], language: AppLanguage) -> String {
        let template = language == .english ? (english[key] ?? key) : key
        let pieces = template.components(separatedBy: "%@")
        guard pieces.count == arguments.count + 1 else { return template }
        // Substitute only the template's placeholders, never user-provided text.
        return zip(arguments, pieces.dropFirst()).reduce(pieces[0]) { $0 + $1.0 + $1.1 }
    }

    static let english: [String: String] = [
        "启用 Finder 扩展": "Enable Finder Extension",
        "点击下方按钮打开系统扩展管理界面，然后启用“右键助手扩展”。如果没有自动定位，可在“系统设置 → 通用 → 登录项与扩展”中查找 Finder 扩展。": "Open extension settings below, then enable “Right-Click Assistant Extension”. If needed, look under System Settings → General → Login Items & Extensions → Finder Extensions.",
        "打开登录项与扩展设置": "Open Login Items & Extensions",
        "正在执行：%@": "Running: %@",
        "已完成：%@": "Completed: %@",
        "执行失败：%@": "Failed: %@",
        "新动作": "New Action",
        "使用应用打开": "Open with App",
        "在终端打开": "Open in Terminal",
        "打开常用目录": "Open Favorite Folder",
        "新建文件": "New File",
        "运行 Shell 脚本": "Run Shell Script",
        "运行 AppleScript": "Run AppleScript",
        "在 %@ 打开": "Open in %@",
        "使用 %@ 打开": "Open with %@",
        "打开 %@": "Open %@",
        "无法执行动作": "Unable to Run Action",
        "动作执行失败": "Action Failed",
        "新建": "New",
        "未命名文稿": "Untitled",
        "\n（输出已截断）": "\n(Output truncated)",
        "退出状态 %@": "Exit status %@",
        "目标应用或目录不存在，请重新编辑此动作。": "The target app or folder no longer exists. Please edit this action.",
        "没有可处理的文件或目录。": "No files or folders to process.",
        "还没有剪切任何项目。": "No items have been cut yet.",
        "上一次粘贴仍在进行，请完成后再试。": "A paste is already in progress. Please wait for it to finish.",
        "脚本内容为空。": "The script is empty.",
        "脚本执行失败：%@": "Script failed: %@",
        "脚本执行超过 30 秒，已停止脚本进程组。": "The script exceeded 30 seconds. Its process group was stopped.",
        "执行请求无效。": "Invalid execution request.",
        "该动作已被停用。": "This action is disabled.",
        "当前文件或目录不符合动作执行条件。": "The selected files or folders do not match this action's conditions.",
        "模板文件名无效。": "Invalid template filename.",
        "系统无法打开目标，请确认目标仍然可用。": "The system could not open the target. Check that it is still available.",
        "系统打开目标超时，请稍后重试。": "Opening the target timed out. Please try again.",
        "脚本进程启动失败（错误码 %@）。": "Could not launch the script process (error %@).",
        "等待脚本进程失败（错误码 %@）。": "Could not wait for the script process (error %@).",
        "读取脚本输出失败（错误码 %@）。": "Could not read script output (error %@).",
        "无法写入系统剪贴板。": "Could not write to the system clipboard.",
        "软件更新": "Software Update",
        "当前 v%@": "Current v%@",
        "GitHub 发布页": "GitHub Releases",
        "取消": "Cancel",
        "关闭": "Close",
        "下载并打开安装包": "Download & Open Installer",
        "重新打开安装包": "Open Installer Again",
        "重新检查": "Check Again",
        "检查 GitHub 上发布的新版本。": "Check GitHub for a new release.",
        "正在检查更新…": "Checking for updates…",
        "当前已是最新版本": "You're up to date",
        "发现新版本 v%@": "Version %@ is available",
        "下载完成后将校验安装包并打开 DMG，请退出右键助手后拖入“应用程序”替换安装。": "The download will be verified and opened as a DMG. Quit Right-Click Assistant, then drag the new app into Applications to replace it.",
        "正在下载 %@%": "Downloading %@%",
        "下载完成，正在校验安装包…": "Download complete. Verifying installer…",
        "安装包校验通过，已打开": "Installer verified and opened",
        "请退出右键助手，将安装包中的应用拖入“应用程序”并替换旧版，然后重新打开。现有动作配置会保留。": "Quit Right-Click Assistant, drag the app from the installer into Applications to replace the old version, then reopen it. Your actions and settings will be preserved.",
        "更新未完成": "Update Not Completed",
        "更新清单无效：请检查版本、HTTPS 安装包地址、SHA-256 和文件大小。": "Invalid update manifest. Check the version, HTTPS installer URL, SHA-256, and file size.",
        "尚未发布更新清单，或更新仓库不可公开访问。": "The update manifest has not been published, or the update repository is not publicly accessible.",
        "更新服务器返回 HTTP %@，请稍后重试。": "The update server returned HTTP %@. Please try again later.",
        "安装包大小与更新清单不符，请重新下载。": "The installer size does not match the manifest. Please download it again.",
        "安装包 SHA-256 校验失败，已丢弃下载文件。": "Installer SHA-256 verification failed. The download was discarded.",
        "无法打开安装包，请从 GitHub 发布页下载安装。": "Could not open the installer. Please download it from GitHub Releases.",
        "此安装包仅支持 Apple Silicon（arm64）。": "This installer only supports Apple Silicon (arm64).",
        "右键助手": "Right-Click Assistant",
        "正在执行 %@ 个动作": "Running %@ actions",
        "最近执行": "Recent Actions",
        "打开右键助手": "Open Right-Click Assistant",
        "扩展设置…": "Extension Settings…",
        "退出右键助手": "Quit Right-Click Assistant",
        "删除分组“%@”？": "Delete group “%@”?",
        "删除分组": "Delete Group",
        "分组内的动作会保留，并移到未分组。": "Actions in this group will be kept and moved to Ungrouped.",
        "配置操作失败": "Configuration Operation Failed",
        "好": "OK",
        "一套动作栈，按当前文件和目录自动显示": "Actions tailored to your files and folders",
        "%@ 项启用 · %@ 项直达": "%@ enabled · %@ favorites",
        "导出配置…": "Export Configuration…",
        "导入配置…": "Import Configuration…",
        "配置备份": "Configuration",
        "搜索动作、类型或分组": "Search actions, types, or groups",
        "收藏显示在一级菜单": "Show favorites at top level",
        "新分组": "New Group",
        "新建分组": "Add Group",
        "执行记录": "Activity",
        "本次运行记录": "This Session",
        "右键助手配置.json": "Right-Click Assistant Configuration.json",
        "导入并替换当前配置？": "Import and replace the current configuration?",
        "文件：%@\n包含 %@ 个动作、%@ 个分组，其中 %@ 个脚本动作。\n\n将替换当前的 %@ 个动作和 %@ 个分组。需要保留当前配置时，请先取消并导出。导入本身不会执行任何动作。": "File: %@\nContains %@ actions and %@ groups, including %@ scripts.\n\nThis will replace your current %@ actions and %@ groups. To keep a backup, cancel and export first. Importing does not execute any actions.",
        "导入并替换": "Import & Replace",
        "配置数据损坏，已使用最近一次有效配置；原始数据已保留用于恢复。": "The configuration is damaged. The last valid backup was loaded; the original data was kept for recovery.",
        "配置数据损坏且没有有效备份，已暂停全部动作；原始数据已保留用于恢复。": "The configuration is damaged and no valid backup is available. All actions are paused; the original data was kept for recovery.",
        "配置来自较新的版本（v%@），当前版本未覆盖它；已使用最近一次有效配置。": "This configuration is from a newer version (v%@). It was not overwritten; the last valid backup was loaded.",
        "配置来自较新的版本（v%@）且没有兼容备份，已暂停全部动作以避免覆盖。": "This configuration is from a newer version (v%@) and no compatible backup is available. All actions are paused to preserve it.",
        "基础动作": "Built-in",
        "复制路径": "Copy Path",
        "复制文件名": "Copy Filename",
        "剪切": "Cut",
        "粘贴已剪切项目": "Paste Cut Items",
        "应用…": "Application…",
        "终端…": "Terminal…",
        "常用目录…": "Favorite Folder…",
        "文件模板": "File Template",
        "Shell 脚本": "Shell Script",
        "添加动作": "Add Action",
        "动作栈": "Actions",
        "清空搜索后可调整顺序": "Clear search to reorder",
        "拖动任意动作可跨类型排序": "Drag actions to reorder across types",
        "%@ 项": "%@ items",
        "没有匹配的动作": "No Matching Actions",
        "更换搜索词，或从右上角添加新动作。": "Try another search or add an action above.",
        "菜单分组": "Menu Groups",
        "拖动分组排序；未分组动作固定显示在最后": "Drag to reorder; ungrouped actions appear last",
        "向前移动": "Move Earlier",
        "向后移动": "Move Later",
        "编辑": "Edit",
        "拖动调整分组顺序，或点击选择前后移动": "Drag to reorder, or click to move earlier or later",
        "修改会即时写入 Finder 配置；脚本、模板与文件移动由右键助手主程序执行。": "Changes apply to Finder immediately. Scripts, templates, and file moves run in the main app.",
        "检查更新": "Check for Updates",
        "未分组": "Ungrouped",
        "选择终端应用": "Choose Terminal App",
        "选择打开文件的应用": "Choose App to Open Files",
        "选择": "Choose",
        "选择常用目录": "Choose Favorite Folder",
        "拖动排序": "Drag to reorder",
        "一级菜单直达": "Top-level favorite",
        "取消一级菜单直达": "Remove from top level",
        "添加到一级菜单": "Add to top level",
        "取消“%@”一级菜单直达": "Remove “%@” from top level",
        "将“%@”添加到一级菜单": "Add “%@” to top level",
        "删除": "Delete",
        "“%@”更多操作": "More options for “%@”",
        "启用“%@”": "Enable “%@”",
        "删除动作“%@”？": "Delete action “%@”?",
        "此操作会立即写入 Finder 配置。": "This change will be saved to Finder immediately.",
        "文件": "Files",
        "文件夹": "Folders",
        "空白处": "Background",
        "限定目录": "Scoped Folders",
        "上移": "Move Up",
        "下移": "Move Down",
        "上移“%@”": "Move “%@” up",
        "下移“%@”": "Move “%@” down",
        "菜单": "Menu",
        "菜单名称": "Menu Name",
        "SF Symbol 图标": "SF Symbol",
        "分组": "Group",
        "不分组": "No Group",
        "启用动作": "Enable Action",
        "收藏到一级右键菜单": "Show in Top-Level Menu",
        "显示条件": "Display Conditions",
        "Finder 空白处": "Finder Background",
        "文件扩展名，例如 md, swift, json；留空表示不限": "File extensions, e.g. md, swift, json; leave empty for any",
        "最少选择 %@ 项": "Select at least %@ items",
        "选择数量和扩展名只用于文件或文件夹；Finder 空白处和工具栏未选择项目时不受这些条件限制。": "Selection counts and extensions apply only to files and folders. They do not limit Finder backgrounds or the toolbar when nothing is selected.",
        "当前动作只显示在 Finder 空白处和工具栏未选择项目时；选择数量与扩展名不适用。": "This action appears only on Finder backgrounds and the toolbar when nothing is selected. Selection counts and extensions do not apply.",
        "作用目录": "Folder Scope",
        "所有目录": "All Folders",
        "移除": "Remove",
        "添加作用目录…": "Add Folder Scope…",
        "所选路径在执行时会再次检查。": "Selected paths are checked again when the action runs.",
        "保存": "Save",
        "操作": "Operation",
        "位置": "Location",
        "未选择": "Not Selected",
        "重新选择应用…": "Choose App Again…",
        "更换应用…": "Change App…",
        "常用目录": "Favorite Folder",
        "更换目录…": "Change Folder…",
        "重新选择目录…": "Choose Folder Again…",
        "扩展名": "Extension",
        "模板内容": "Template Content",
        "所选路径会作为 $1、$2… 传入；$RCA_DIRECTORY 是当前目录。": "Selected paths are passed as $1, $2, …; $RCA_DIRECTORY contains the current folder.",
        "所选路径会传给 on run argv。": "Selected paths are passed to on run argv.",
        "粘贴": "Paste",
        "未知": "Unknown",
        "最多选择 %@ 项": "Select at most %@ items",
        "选择数量不设上限": "No selection limit",
        "菜单名称不能为空。": "The menu name cannot be empty.",
        "至少选择一种显示位置。": "Choose at least one display context.",
        "模板名称不能是 . 或 ..，也不能包含路径分隔符。": "The template name cannot be . or .., or contain path separators.",
        "模板扩展名不能为空。": "The template extension cannot be empty.",
        "模板扩展名不能是 . 或 ..，也不能包含路径分隔符。": "The template extension cannot be . or .., or contain path separators.",
        "脚本内容不能为空。": "The script cannot be empty.",
        "选择动作生效的目录": "Choose a Folder Scope",
        "添加": "Add",
        "分组名称": "Group Name",
        "创建": "Create",
        "应用": "Application",
        "终端": "Terminal",
        "复制所选项目的完整路径": "Copy the full paths of selected items",
        "复制所选项目的名称": "Copy the names of selected items",
        "记录所选项目，稍后移动到目标文件夹": "Remember selected items to move into another folder later",
        "把已剪切项目移动到当前文件夹": "Move the cut items into the current folder",
        "基础 Finder 动作": "Built-in Finder action",
        "选择一个应用": "Choose an app",
        "选择一个终端应用": "Choose a terminal app",
        "选择一个常用目录": "Choose a favorite folder",
        "新建 .%@ 文件": "Create a .%@ file",
        "通过 zsh 执行；所选路径作为位置参数传入": "Run with zsh; selected paths are passed as positional arguments",
        "通过 osascript 执行；所选路径作为参数传入": "Run with osascript; selected paths are passed as arguments",
        "打开方式": "Open With",
        "新建文本文件": "New Text File",
        "无法导入版本 %@ 的配置，请使用兼容版本的右键助手。": "Cannot import configuration version %@. Please use a compatible version of Right-Click Assistant.",
        "配置格式无效，或包含重复标识、空名称或无效分组。": "Invalid configuration format, duplicate identifiers, empty names, or invalid groups.",
        "常用 Finder 操作": "Common Finder Actions",
        "右键助手主程序未安装或无法启动。": "Right-Click Assistant is not installed or could not be launched.",
        "无法定位右键助手主程序。": "Could not locate the Right-Click Assistant app.",
        "语言": "Language",
        "界面语言": "Interface Language",
        "界面和 Finder 菜单会即时切换。Dock 名称在重新打开应用后刷新。": "The interface and Finder menus update immediately. The Dock name refreshes after reopening the app.",
        "右键助手扩展": "Right-Click Assistant Extension",
    ]
}
